### ISSUE TITLE
Support moving files within selected text in a note

### ISSUE THREAD

**Issue by wenlzhang** [ivaneye/obsidian-files-cooker#1]
One may have a project page/note where several note links are inserted there. After the project is completed, the linked notes there can be moved into an archive folder. Therefore, it would be great if one can select some text within a note, and then use this plugin to move all notes contained in the selected text to a desired folder.

**Comment by ivaneye** [comment]
> One may have a project page/note where several note links are inserted there. After the project is completed, the linked notes there can be moved into an archive folder. Therefore, it would be great if one can select some text within a note, and then use this plugin to move all notes contained in the selected text to a desired folder.

New version 1.1.0!
Support to move all links in active file to target folder!
