### ISSUE TITLE
Move Dataview Query Results -> Command not available in the command palette 

### ISSUE THREAD

**Issue by renatomen** [ivaneye/obsidian-files-cooker#12]
### Symptom
Move Dataview Query Results -> Command not available in the command palette.
Symptom occurs both in Read / Live Preview modes.

### Steps to reproduce
1. Navigate to a note that displays Dataview Results
2. Display the command palette
3. Search for FileCooker command

### Unexpected result
- "Move Dataview Query Results" command is NOT available for selection.
![image](https://user-images.githubusercontent.com/7007954/210037008-26b7f055-2e79-456d-9702-4b4bec5fdf07.png)

### Expected result
- "Move Dataview Query Results" command is available for selection

### Additional Comments
- Obsidian v1.1.9
- Plugins installed: 2 -> File Cooker 1.6.5, Dataview 0.5.47
- OS: Windows 11

**Comment by renatomen** [comment]
@ivaneye , this is really intriguing.

All dataview options are available in my main vault, which has dozens of other plugins installed.
Both my test vault and my main vault have the same Obsidian version, Dataview version and File Cooker version.
The only difference are

### Main Vault:
- Dozens of other plugins installed
- Thousands of notes
- File Cooker dataview commands are only available in "Live Preview" mode. Not available in "Reading" mode.

### Test Vault
- Created from scratch to test FileCooker
- Has only 4 notes
- Only Dataview and FileCooker installed initially.
- Then I tested with "Metaedit" plugin installed to see if it would make any difference, which it didn't.

Here's what I see in my main vault. However, if I try to move based on dataview results, i get a
`Query String Error![],`  which I'll report in a separate issue:
![image](https://user-images.githubusercontent.com/7007954/210039401-74073e21-68f1-47e0-9b99-1cd2581ed0a7.png)

**Comment by ivaneye** [comment]
e～ 
The command which use dataview needs you to select the dataview query ,just like this
<img width="737" alt="iShot_2022-12-30_14 08 44" src="https://user-images.githubusercontent.com/1344938/210039927-8e962735-2f48-4657-ba21-d5bf31b74bf8.png">

**Comment by renatomen** [comment]
Thanks @ivaneye 

It worked as expected in my Main vault, which contains dozens of plugins. 
However, It didn't work on a new vault created only to test File Cooker. The "Move Dataview Query Results" are not available on that vault even when I select the query text as you described.

Below are the debug info from both vaults:

# Main Vault (Where the command is displayed and works as expected)
`SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.1.9
	Operating system: Windows 10 Home 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: LYT Mode v1.5.0
	Snippets enabled: 11
	Restricted mode: off
	Plugins installed: 67
	Plugins enabled: 58
		1: Dataview v0.5.47
		2: Plugin Update Tracker v1.4.3
		3: File Cooker v1.6.5
		4: Obsidian42 - BRAT v0.6.36
		5: Snippet Downloader v2.0.1
		6: Markdown Attributes v1.2.2
		7: Advanced URI v1.31.2
		8: Auto Link Title v1.2.5
		9: Banners v1.3.3
		10: Better Word Count v0.9.1
		11: Calendar v1.5.10
		12: Contextual Typography v2.2.4
		13: Convert url to preview (iframe) v0.5.0
		14: DB Folder v3.1.3
		15: Diagrams v1.5.0
		16: Editor Syntax Highlight v0.1.3
		17: Excalidraw v1.8.7
		18: ExcaliBrain v0.1.11
		19: Excel to Markdown Table v0.4.0
		20: Full Calendar v0.9.5
		21: Hider v1.2.4
		22: Hover Editor v0.11.8
		23: Jira Issue v1.48.0
		24: Kanban v1.5.1
		25: MAKE.md v0.5.6
		26: Metadata Menu v0.4.3
		27: MetaEdit v1.7.2
		28: Metatable v0.14.3
		29: Mind Map v1.1.0
		30: Minimal Theme Settings v6.1.1
		31: Natural Language Dates v0.6.1
		32: Note Refactor v1.7.1
		33: obsidian markmind v1.6.4
		34: Omnisearch v1.9.1
		35: Outliner v4.2.1
		36: Periodic Notes v1.0.0-beta.3
		37: Projects v1.8.0
		38: Quick Explorer v0.2.7
		39: QuickAdd v0.8.0
		40: Quiet Outline v0.3.14
		41: Reminder v1.1.15
		42: Settings Search v1.2.0
		43: Sortable v0.2.6
		44: Style Settings v0.4.12
		45: Tag Navigator v0.5.0
		46: Tag Wrangler v0.5.5
		47: Taskbone v1.2.3
		48: Taskbone OCR v1.0.0
		49: Tasks v1.21.0
		50: Templater v1.16.0
		51: Text Generator v0.1.22
		52: Todoist Plugin v1.10.1
		53: Todoist Link v2.2.0
		54: Tracker v1.10.9
		55: Zoom v1.1.1
		56: Image Toolkit v1.3.1
		57: Ozan's Image in Editor Plugin v2.1.6
		58: Advanced Tables v0.18.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
`

# Test Valut - Where the command doesn't work (not available for selection in the palette)
`SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.1.9
	Operating system: Windows 10 Home 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 3
	Plugins enabled: 3
		1: File Cooker v1.6.5
		2: Dataview v0.5.47
		3: MetaEdit v1.7.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
`

**Comment by ivaneye** [comment]
try to restart obsidian?
The "Move Dataview Query Results" should display when Dataview and MetaEdit installed!
if it still doesn't work, send your test vault  to me, I will try on my computer.

**Comment by renatomen** [comment]
Thanks @ivaneye 

Didn't work on the freshly installed vault.

Things I tried:
- Restarted obsidian (multiple times)
- Reinstalled Dataview, MetaEdit
- Enabled and disabled Dataview Options (Enable javascript, inline Js etc..)

I'm attaching the vault here for you.
[Cooker.zip](https://github.com/ivaneye/obsidian-files-cooker/files/10328063/Cooker.zip)

**Comment by ivaneye** [comment]
> Thanks @ivaneye
> 
> Didn't work on the freshly installed vault.
> 
> Things I tried:
> 
> * Restarted obsidian (multiple times)
> * Reinstalled Dataview, MetaEdit
> * Enabled and disabled Dataview Options (Enable javascript, inline Js etc..)
> 
> I'm attaching the vault here for you. [Cooker.zip](https://github.com/ivaneye/obsidian-files-cooker/files/10328063/Cooker.zip)

try disabled and enabled file-cooker。
<img width="836" alt="iShot_2023-01-03_08 01 04" src="https://user-images.githubusercontent.com/1344938/210286073-4b11e6f1-5327-4246-b1d7-49a730e7509e.png">

**Comment by renatomen** [comment]
Thanks @ivaneye  

Disabling and re-enabling the File-Cooker plugin resolved the issue.
Dataview options immediately appeared in the command palette.

![image](https://user-images.githubusercontent.com/7007954/210671371-61a6d082-1bb8-4daa-ba1c-581c49884ef2.png)
