### ISSUE TITLE
Query String Error! [] When using "Move Dataview Query Results" command

### ISSUE THREAD

**Issue by renatomen** [ivaneye/obsidian-files-cooker#13]
### Symptom
When I use "Move Dataview Query Results" command, a toast notification displays the error:

`Query string error![ ]`

### Steps to reproduce
1. Open a note containing a dataview query with 1 or more results listed
2. Open the command palette and select "Move Dataview Query Results"
3. Select the destination folder
4. Select "Move"

### Unexpected results
A toast notification displays the error:
`Query string error![ ]`

### Expected results
The dataview results are moved to the target folder

![image](https://user-images.githubusercontent.com/7007954/210039619-0d7cf98c-0295-4e78-96f8-726c1cd2cc24.png)
![image](https://user-images.githubusercontent.com/7007954/210039923-dba98c1b-e292-4372-8ff1-ab49db8a2651.png)

Additional Comments
Obsidian v1.1.9
Plugins installed: Dozens -> File Cooker 1.6.5, Dataview 0.5.47
OS: Windows 11

**Comment by ivaneye** [comment]
<img width="737" alt="iShot_2022-12-30_14 08 44" src="https://user-images.githubusercontent.com/1344938/210040043-5f4278bb-d4ad-40c1-be2e-08e6ccf410f6.png">

**Comment by renatomen** [comment]
Thanks @ivaneye . The Query string Error is resolved!
I made a comment on the #12  which is still not working on a freshly created vault. The vault debug info was included.
I"m closing this one. Thanks for the amazing work 🙏
