### ISSUE TITLE
Support moving files satisfying certain Dataview results to a certain folder

### ISSUE THREAD

**Issue by wenlzhang** [ivaneye/obsidian-files-cooker#2]
With Dataview, one can query notes by setting several conditions, e.g., from certain folders, with certain tags, having certain fields, etc. It would be great if one can move all notes from query results to a folder by using one command.

https://github.com/blacksmithgu/obsidian-dataview

**Comment by ivaneye** [comment]
I will release a new version this week!

**Comment by ivaneye** [comment]
> With Dataview, one can query notes by setting several conditions, e.g., from certain folders, with certain tags, having certain fields, etc. It would be great if one can move all notes from query results to a folder by using one command.
> 
> https://github.com/blacksmithgu/obsidian-dataview

v1.3.0 is released! You can try it!
Support :
- move dataview results to target folder 
- delete dataview results

**Comment by wenlzhang** [comment]
I tried to move notes in a folder to another folder but it gives me the error message: `Query error![]`

Specifically, I used the following Dataview code to get the query results:
```dataview
TABLE file.day, file.mtime FROM "800-Dataview and test/Test Dataview"
```

I am testing with Obsidian 0.15.4 and Dataview 0.54.1.

Not sure if it is relevant, but I observed that the release for version 1.3.0 actually has the version number 1.2.0.

**Comment by wenlzhang** [comment]
And I did not see any other messages in the console when executing the moving files command.

**Comment by ivaneye** [comment]
> I tried to move notes in a folder to another folder but it gives me the error message: `Query error![]`
> 
> Specifically, I used the following Dataview code to get the query results:
> 
> ```
> TABLE file.day, file.mtime FROM "800-Dataview and test/Test Dataview"
> ```
> 
> I am testing with Obsidian 0.15.4 and Dataview 0.54.1.
> 
> Not sure if it is relevant, but I observed that the release for version 1.3.0 actually has the version number 1.2.0.

I have updated new files to v1.3.0。Please re-download v1.3.0。

**Comment by wenlzhang** [comment]
I updated to version 1.3.0 and tested with the following query example. However, I got the notification "No files found!" and the following error message in the console.

The query example:

```
List FROM "800-Dataview and test/Test Dataview"
```

The message from the console:

```
{
    "error": "Error: \n-- PARSING FAILED --------------------------------------------------\n\n> 1 | ```DATAVIEW\n    | ^\n  2 | LIST FROM \"800-DATAVIEW AND TEST/TEST DATAVIEW\"\n  3 | ```\n\nExpected:\n\nTABLE or LIST or TASK or CALENDAR\n",
    "successful": false
}
```

**Comment by ivaneye** [comment]
> I updated to version 1.3.0 and tested with the following query example. However, I got the notification "No files found!" and the following error message in the console.
> 
> The query example:
> 
> ```
> List FROM "800-Dataview and test/Test Dataview"
> ```
> 
> The message from the console:
> 
> ```
> {
>     "error": "Error: \n-- PARSING FAILED --------------------------------------------------\n\n> 1 | ```DATAVIEW\n    | ^\n  2 | LIST FROM \"800-DATAVIEW AND TEST/TEST DATAVIEW\"\n  3 | ```\n\nExpected:\n\nTABLE or LIST or TASK or CALENDAR\n",
>     "successful": false
> }
> ```

Try v1.3.1。
The Dataview's function query() is case sensitive。
To upper case the command before invoking function query()。

**Do not select the wrapping string like 「```dataview」 !!! Select the query string only!!!**

**Comment by wenlzhang** [comment]
Great! It works for both `list` and `table` now!

**Comment by ivaneye** [comment]
> Great! It works for both `list` and `table` now!

It works for task too。
