### ISSUE TITLE
Support copying instead?

### ISSUE THREAD

**Issue by joellti** [ivaneye/obsidian-files-cooker#4]
Reason being sometimes I just want to create a copy of these files somewhere else just for sharing purpose for example. Let me know if it's something you will consider implementing which will be great addition to the plugin.

**Comment by ivaneye** [comment]
Copy multi-file to target folder like Move-Action?

**Comment by ivaneye** [comment]
> Reason being sometimes I just want to create a copy of these files somewhere else just for sharing purpose for example. Let me know if it's something you will consider implementing which will be great addition to the plugin.

Copy multi-file to target folder like Move-Action?

**Comment by joellti** [comment]
yes

**Comment by ivaneye** [comment]
> yes. just have another related question. when you move files do you also move the attachments that these files are linking to?

The plugin just move the selected files and update all links to them。

I can add Copy-Action, but there is a problem, if you have two files , they are linking to each other。After you copy the two files to a new folder，they still link to the old files。

**Comment by joellti** [comment]
ideally the copy operation should clone not just the selected note files but also the ones they link to, and even the ones the latter ones link to, so on and so forth and i think it will address your question. but i think it's a lot work so i don't know if you would like to tackle this..

**Comment by ivaneye** [comment]
I can add function to copy the target note files first.
the sub-links i may deal later~

**Comment by joellti** [comment]
great. thx for your consideration. i look forward to your next version.

**Comment by ivaneye** [comment]
try v1.4.1
You can choose move or copy multi-file to target folder on MoveConfirmModal
<img width="567" alt="iShot_2022-08-11_19 37 00" src="https://user-images.githubusercontent.com/1344938/184124997-5d01a523-44ed-4324-a34b-7c3df4d0eea3.png">
