### ISSUE TITLE
BUG?  plugin install and update broken - under Obsidian  v0.16.2

### ISSUE THREAD

**Issue by Sigbert11** [ivaneye/obsidian-files-cooker#5]
used to work all fine some days ago - till update to Obsidian v. 0.16.2 ( which  brought a lot of changes ).

**now:** 
- either UPDATE  and (after deinstall) INSTALL reports:  `failed ...`

Any suggestions?

**Comment by ivaneye** [comment]
> used to work all fine some days ago - till update to Obsidian v. 0.16.2 ( which brought a lot of changes ).
> 
> **now:**
> 
> * either UPDATE  and (after deinstall) INSTALL reports:  `failed ...`
> 
> Any suggestions?

I can not update to V0.16.* now。
I will fix this when V0.16.* released。

**Comment by Superfeuchter** [comment]
I could not install the plugin either ... v0.16.2

**Comment by Sigbert11** [comment]
https://github.com/ivaneye/obsidian-files-cooker/issues/5#issuecomment-1240235965

Now works again
Thank you for fixing it.
