### ISSUE TITLE
Only move the last file when list is copied from Obsidian search result

### ISSUE THREAD

**Issue by LinuxOrNot** [ivaneye/obsidian-files-cooker#8]
With the command "Move files...", Files Cooker only move the last file. I really don't know why. 

Here's an example.

![image](https://user-images.githubusercontent.com/66257676/195471176-be3297c6-593a-4506-8224-c9852b59fece.png)

![image](https://user-images.githubusercontent.com/66257676/195471241-fdb8d18c-358d-4aef-82d9-aa00ba94b615.png)

**Comment by ivaneye** [comment]
which version do you use?

**Comment by LinuxOrNot** [comment]
[image.png]

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by renatomen** [comment]
Hi Ivan.

I have the same problem.

### Steps to reproduce:
1. Search notes using obsidian standard search
2. Copy search results to clipboard (including path).
3. Open the command Palette and select "File Cooker: Move files to..."

### Unexpected results:

- Only the last file of the selected files list is displayed in the "Confirm Move/Copy" screen.
- Only the last file of the selected files list is moved

![image](https://user-images.githubusercontent.com/7007954/210035138-5fb8ab74-e635-42c0-9dfe-3343f0fa5114.png)
![image](https://user-images.githubusercontent.com/7007954/210035153-d4546ac7-7986-48ba-b6ec-f9e80ccf7e5a.png)



### Expected results
- All files copied to clipboard are displayed in the "Confirm Move/Copy" screen
- All selected files are moved

### Additional comments:
- Version 1.6.5 was working fine until recently.
- The results above were obtained with
    -  Obsidian v1.1.9
    -  Only File Cooker plugin enabled (all other plugins disabled).
 
Given the fact that the plugin was working before and also the fact that no other plugin could be interfering with it, I wonder if the unexpected behaviour is related to recent Obsidian App Updates.
