### ISSUE TITLE
Support adding all notes from Dataview query results to Canvas

### ISSUE THREAD

**Issue by wenlzhang** [ivaneye/obsidian-files-cooker#9]
Obsidian version 1.1.0 support Canvas feature. Basically, one can add notes to a canvas and build connections, just like Hepta and Scrintal.

It would be great one can achieve the following with this plugin:

- Use a Dataview query to search for desired notes
- Send all notes from the query result to a desired canvas file

After this, one can use the Canvas feature as normal.

**Comment by ivaneye** [comment]
I will try after new version released~

**Comment by ivaneye** [comment]
v1.7.0 is released! 
Support:
- add all notes from DataView query results to Canvas
- add all links in current file to Canvas
- add all file paths in clipboard to Canvas

**Comment by wenlzhang** [comment]
Thanks for the update! It works like a charm!
